---
title: "Practice 4.1"
author: "Annie"
date: "2024-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Practice 4.1

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



```{r, echo=FALSE}
pdf(file = "Practice 4.1.pdf", paper = "A4")


data(iris)


plot(iris$Petal.Length, iris$Petal.Width,
     xlab = "Petal length (cm)", 
     ylab = "Petal width (cm)",
     main = "Petal width vs. length",
     cex.main = 1.5,  #字體大小
     pch = c(1, 2, 3)[as.numeric(iris$Species)], ## 點形狀根據物種改變 
     col = c("black", "red", "green")[as.numeric(iris$Species)])  

# 斜線
model <- lm(Petal.Width ~ Petal.Length, data = iris) #lm()函數建立一個線性回歸模型，來預測Petal.Width（花瓣寬度），根據自變量 Petal.Length（花瓣長度）。
abline(model, col = "black", lwd = 2)#在現有的圖形上加一條線


#  legend
legend("topleft", legend = levels(iris$Species),# 圖例標籤來自 Species 層級
       pch = c(1, 2, 3), 
       col = c("black", "red", "green"),
       )

# correlation coefficient
r_value <- summary(model)$r.squared
text(5.5, 0.5, labels = paste("R = ", round(sqrt(r_value), 2)), pos = 4)



dev.off()

```



